[[packages]]
name = "pikascript-core"
releases = [
  "v0.8.1 af42fd61884dc7048628b0d3bafaa42697f6e8ea",
  "v0.8.2 af42fd61884dc7048628b0d3bafaa42697f6e8ea",
  "v0.8.3 af42fd61884dc7048628b0d3bafaa42697f6e8ea",
  "v0.9.0 332ef8afb0692cddd194782a07e30f2688d0f813",
  "v0.10.0 c86eaefa4516dd82b1050fa74a7d85399459d5ed",
  "v1.0.0 7b816b1546ef91a03f77760d4b10806ab956d452",
  "v1.1.0 845d1fc6520237e2238087800f72608dcb81afa6",
  "v1.1.1 c77e42450ed0eb09fcd7bb2b7d7c2b7eeeb55a2e",
  "v1.1.2 f6ad2c78f49162ab3f898abc6a0a4d87777ce655",
  "v1.1.3 6539072bf7bebb242ea40f8595bfb5c9aae3de7f",
  "v1.2.0 ce3df083b68fbfc85e64e6793fe07a6736d6f29f",
  "v1.2.1 e29a77527fd753c4eb811b047899534472bfc8ec",
  "v1.2.2 5316ede928b01a20571103616a64666abbc40e0a",
  "v1.2.3 5ae86929851ff6a62342a7072b77e9cf5be85f1c",
  "v1.2.4 b7ac057d75e88736cc844de0bafb447a48f2fb6d",
  "v1.2.5 db51f0520a673074a14ef0f5c4434da0d5c3425f",
  "v1.2.6 aafc990cdf1dccf6be1944de8c6456a6135c98b1",
  "v1.2.7 1c469e1871002df28b0c531828e20f283dc15d36",
  "v1.2.8 3ad17a46b83eec46d2c493761a67ab0d0c492159",
  "v1.2.9 c35940141816c74e164c83c38bcdab7d6ffe1a2f",
  "v1.3.0 3032d3d05423b5f3dd2a4efe1f8eadd1d835f58f",
  "v1.3.1 343a1d56c53bba78fce9a0cd0cc8dfcd580632be",
  "v1.3.2 b54cd1ed5ae45c4f5789e266ea1f4f2e420ec306",
  "v1.3.3 520a1cfb49e7c9e6bfca84a140fd80b0c2b0e000",
  "v1.3.4 c205fc00f1503135bdf6890ebfb61ebaf7d23445",
  "v1.3.5 80d255e8efbf718a7bd6cac9cf8478a6e2e72a37",
  "lts2021 80d255e8efbf718a7bd6cac9cf8478a6e2e72a37",
  "v1.3.5.1 9ebdaa5560c04f53af13743d00a5b7a8f00c0508",
  "v1.4.0 3b9dcd1b0c11e20a8e499e352b776d2996e9e291",
  "v1.4.1 a0cad21ed9f1d263f8c2274a38f92e2fa6d50bfd",
  "v1.5.0 a512ab3e4cd0e71a15b5169a1879322c66c139c3",
  "v1.5.1 3fafffee54f5d7e6b9776b44300be696abd47112",
  "v1.5.2 ed489e20708528e084d189126f443902f613a4f3",
  "v1.5.3 0c8641191624003de9d675c07895de2438b9edaa",
  "v1.5.4 307be4d77a4ea091834ba687ed7e9d217f83c6ea",
  "v1.6.0 634a82135f4213b078cc9bf2d8e1ec287cc3ad2f",
  "v1.6.1 9e24f8f7c8b39faa72f04935379be3b21a4f0545",
  "v1.6.2 fa56cc085a53cde6759df11c975b25f93dc7bd48",
  "v1.6.3 1e42f65a99b8e50619adaa13ca4b0b30123a05ac",
  "v1.6.4 7362ba0d4b55abc304d3169989370f0dd8cddde0",
  "v1.6.5 3fae2b5e86a0de787f6785ccd72a6590b4984f88",
  "v1.7.0 7435342e984d02c7cff719a2aa935ea1c53dd246",
  "v1.7.1 7345c222bd446bad6eb32a32f38cad36867fba7c",
  "v1.7.2 ff3243a0c829c713e112f5b42b0e3abe55c08a2e",
  "v1.8.0 6724a2a56bebf8c3595260ef702c03fafd7143eb",
  "v1.8.1 2a90da5b07f0a14218be6a5c6e21be0f79b32e48",
  "v1.8.2 281600804a5393c6721eab8ec6160a376ba010b4",
  "v1.8.3 3c7b765a3f9116cc7653491d067760912a5e7237",
  "v1.8.4 65a4c6bf0262ebbfa269b9c514d726f64a912f10",
  "v1.8.5 cbde99793b1e631ab7f54775cba3f5372895b560",
  "v1.8.6 f30dd75da12699e1aa787acc3111bf7730c4c082",
  "v1.8.7 88f015bcb2bc5dd1260f35125822b2ba4535d861",
  "v1.8.8 9d10e05b081db8a4b34c4923c5e58121e2896fab",
  "v1.9.0 6bf9f03db4416cf222fb6c8e8c9a0ecd06fb40a4",
  "v1.9.1 e136c84c834e21d58edc896f0780a86ae179c0a8",
  "v1.9.2 cf7876efdaf92f9f92e25370066f811f6892a5cb",
  "v1.10.0 211569c5a0169dbb700885d21fbbe0c678126e9e",
  "v1.10.1 1578eacdea69766dcebc2017a99c4fade19ef53f",
  "v1.10.2 d3669ee95de98eb85e6a264aa28825ce7a011a11",
  "v1.10.3 11088f6b4ba3d5b545fe4bfdc8c27ab4fbe01936",
  "v1.10.4 f09ea25237cd35a27fd071198ff771c8b4a088ad"
]

[[packages]]
name = "PikaStdLib"
releases = [
  "v1.0.1 af42fd61884dc7048628b0d3bafaa42697f6e8ea",
  "v1.1.0 0b3b866dbacc363c7b6b3899faa0cbcaccd59d5e",
  "v1.2.0 ca29e112687525ee7511bd30418d368754627a00",
  "v1.2.1 5ae86929851ff6a62342a7072b77e9cf5be85f1c",
  "v1.2.2 b7ac057d75e88736cc844de0bafb447a48f2fb6d",
  "v1.2.3 85aa32b4831ede9de2657dd4cdd22e1310b1cde8",
  "v1.2.4 3ad17a46b83eec46d2c493761a67ab0d0c492159",
  "v1.2.5 c35940141816c74e164c83c38bcdab7d6ffe1a2f",
  "v1.3.0 5eedf8be911f4c389c5496a79b600004077039f5",
  "v1.3.1 343a1d56c53bba78fce9a0cd0cc8dfcd580632be",
  "v1.3.2 b54cd1ed5ae45c4f5789e266ea1f4f2e420ec306",
  "v1.3.3 520a1cfb49e7c9e6bfca84a140fd80b0c2b0e000",
  "v1.3.4 c205fc00f1503135bdf6890ebfb61ebaf7d23445",
  "v1.3.5 3e87db85ca2171991f77bd3af59c4eaefed69110",
  "lts2021 3e87db85ca2171991f77bd3af59c4eaefed69110",
  "v1.3.5.1 9ebdaa5560c04f53af13743d00a5b7a8f00c0508",
  "v1.4.0 3b9dcd1b0c11e20a8e499e352b776d2996e9e291",
  "v1.4.1 a0cad21ed9f1d263f8c2274a38f92e2fa6d50bfd",
  "v1.5.0 a512ab3e4cd0e71a15b5169a1879322c66c139c3",
  "v1.5.1 3fafffee54f5d7e6b9776b44300be696abd47112",
  "v1.5.2 ed489e20708528e084d189126f443902f613a4f3",
  "v1.5.3 0c8641191624003de9d675c07895de2438b9edaa",
  "v1.5.4 307be4d77a4ea091834ba687ed7e9d217f83c6ea",
  "v1.6.0 634a82135f4213b078cc9bf2d8e1ec287cc3ad2f",
  "v1.6.1 9e24f8f7c8b39faa72f04935379be3b21a4f0545",
  "v1.6.2 fa56cc085a53cde6759df11c975b25f93dc7bd48",
  "v1.6.3 1e42f65a99b8e50619adaa13ca4b0b30123a05ac",
  "v1.6.4 7362ba0d4b55abc304d3169989370f0dd8cddde0",
  "v1.6.5 3fae2b5e86a0de787f6785ccd72a6590b4984f88",
  "v1.7.0 7435342e984d02c7cff719a2aa935ea1c53dd246",
  "v1.7.1 7345c222bd446bad6eb32a32f38cad36867fba7c",
  "v1.7.2 ff3243a0c829c713e112f5b42b0e3abe55c08a2e",
  "v1.8.0 6724a2a56bebf8c3595260ef702c03fafd7143eb",
  "v1.8.1 2a90da5b07f0a14218be6a5c6e21be0f79b32e48",
  "v1.8.2 281600804a5393c6721eab8ec6160a376ba010b4",
  "v1.8.3 3c7b765a3f9116cc7653491d067760912a5e7237",
  "v1.8.4 65a4c6bf0262ebbfa269b9c514d726f64a912f10",
  "v1.8.5 cbde99793b1e631ab7f54775cba3f5372895b560",
  "v1.8.6 f30dd75da12699e1aa787acc3111bf7730c4c082",
  "v1.8.7 88f015bcb2bc5dd1260f35125822b2ba4535d861",
  "v1.8.8 9d10e05b081db8a4b34c4923c5e58121e2896fab",
  "v1.9.0 0892f1d426e3d69daaff1251d8e45d2ef60d1ad4",
  "v1.9.1 e136c84c834e21d58edc896f0780a86ae179c0a8",
  "v1.9.2 cf7876efdaf92f9f92e25370066f811f6892a5cb",
  "v1.10.0 211569c5a0169dbb700885d21fbbe0c678126e9e",
  "v1.10.1 1578eacdea69766dcebc2017a99c4fade19ef53f",
  "v1.10.2 d3669ee95de98eb85e6a264aa28825ce7a011a11",
  "v1.10.3 11088f6b4ba3d5b545fe4bfdc8c27ab4fbe01936",
  "v1.10.4 f09ea25237cd35a27fd071198ff771c8b4a088ad"
]

[[packages]]
name = "PikaStdDevice"
releases = [
  "v1.3.0 af42fd61884dc7048628b0d3bafaa42697f6e8ea",
  "v1.4.0 29c3c5b3b0cb4d3e41e6a2a0aef9e2826bc6f7ba",
  "v1.4.1 6539072bf7bebb242ea40f8595bfb5c9aae3de7f",
  "v1.4.2 5ae86929851ff6a62342a7072b77e9cf5be85f1c",
  "v1.4.3 17cc05c42cc26e694475a6c19f8d0712f8768750",
  "v1.4.4 ac4247e5fd3e221eb110a1b41276849c623049ec",
  "v1.5.0 a512ab3e4cd0e71a15b5169a1879322c66c139c3",
  "v1.6.0 240f073472217ca6c3d6d04d5a860056f2c0b7d4",
  "v1.7.0 7826f74c839b5ecb3bd5d832c3f0b2e757acf2e6",
  "v1.8.0 9f3a52558338503571b37c034a12219566f27aa2",
  "v1.8.2 281600804a5393c6721eab8ec6160a376ba010b4",
  "v1.8.6 e88cf95105343f3246ac76795d599d5c209c1ab3",
  "v1.8.7 88f015bcb2bc5dd1260f35125822b2ba4535d861",
  "v1.9.0 0892f1d426e3d69daaff1251d8e45d2ef60d1ad4",
  "v1.10.0 211569c5a0169dbb700885d21fbbe0c678126e9e",
  "v1.10.2 d3669ee95de98eb85e6a264aa28825ce7a011a11",
  "v1.10.3 11088f6b4ba3d5b545fe4bfdc8c27ab4fbe01936",
  "v1.10.4 f09ea25237cd35a27fd071198ff771c8b4a088ad"
]

[[packages]]
name = "PikaMath"
releases = [
  "v0.0.1 31146e2395e80b5785a4b2e526913a4590160e66",
  "v0.1.0 793634882044af25f30bb59c6511c615e56f85c5",
  "v0.2.0 211569c5a0169dbb700885d21fbbe0c678126e9e"
]

[[packages]]
name = "PikaCV"
releases = [
  "v0.0.1 b463e812bf0334b55835a3b31cda0c2f6c526e06",
  "v0.1.0 211569c5a0169dbb700885d21fbbe0c678126e9e"
]

[[packages]]
name = "unittest"
releases = [ "v0.1.0 cd6dfbbb714228e7e0f147515d58450644e7dadf" ]

[[packages]]
name = "socket"
releases = [ "v0.1.0 f09ea25237cd35a27fd071198ff771c8b4a088ad" ]

[[packages]]
name = "random"
releases = [ "v0.1.0 7244267b6839b8af2238b6cdd9a73e4a3aebb347" ]

[[packages]]
name = "configparser"
releases = [
  "v0.1.0 d3a9f6e226bb9cfccbfc588cc465672cefea9e82",
  "v0.2.0 211569c5a0169dbb700885d21fbbe0c678126e9e"
]

[[packages]]
name = "ctypes"
releases = [
  "v0.0.1 7362ba0d4b55abc304d3169989370f0dd8cddde0",
  "v0.0.2 3fae2b5e86a0de787f6785ccd72a6590b4984f88",
  "v1.0.0 cbde99793b1e631ab7f54775cba3f5372895b560",
  "v1.0.1 5148412411e2de0d23e9c5857b0b4843f479a5be",
  "v1.1.0 211569c5a0169dbb700885d21fbbe0c678126e9e"
]

[[packages]]
name = "binascii"
releases = [ "v0.0.1 88896715867c2a89df3e3b733cba38cc84f5347c" ]

[[packages]]
name = "pika_cjson"
releases = [
  "v0.0.1 60389c541db480f41a55498270094dd030df9e24",
  "v1.0.0 cbde99793b1e631ab7f54775cba3f5372895b560",
  "v1.1.0 0cf260fca1e7613dc5523fd09de00df952c9dbd3",
  "v1.1.1 68b28c780861190639452ed0642e2f4064fa44c3",
  "v1.2.0 211569c5a0169dbb700885d21fbbe0c678126e9e"
]

[[packages]]
name = "pika_lvgl"
releases = [
  "v0.0.1 71364445e0894e660720f9a0c9e1db021663d6a1",
  "v0.1.0 027f06710e83ee3daa7b706fb8a9bf23b1ab14e4",
  "v0.2.0 871fbf701c24c9c05792d3c551c44b699f4de7bf"
]

[[packages]]
name = "pika_lua"
releases = [ "v0.0.1 b5da16e285a378a74fa7b7734cdd89be703d6f07" ]

[[packages]]
name = "pikaRTThread"
releases = [
  "v1.0.0 3509764a2ed63c565e63f61814e9b656fc573841",
  "v1.0.1 e8bb5a8d18516f79da7115f73024cae70fa51590",
  "v1.1.0 ff2e72ccb08c6a5935ed7ed77dfaa3a074ff120f",
  "v1.1.1 ac4247e5fd3e221eb110a1b41276849c623049ec",
  "v1.2.0 e2e94bb3a349985641fa686341757cfbd18207e2",
  "v1.3.0 9f3a52558338503571b37c034a12219566f27aa2"
]

[[packages]]
name = "PikaVSF"
releases = [ "v0.0.1 f755ec10042f4deefef1c5491f5e91a651f71a1b" ]

[[packages]]
name = "Arm2D"
releases = [
  "v0.0.1 af42fd61884dc7048628b0d3bafaa42697f6e8ea",
  "v0.1.0 1b0384c5b20e336645b24df808f98548912405b8",
  "v0.2.0 83f2639bf61a3b000a9bae5c5977bd67afdf57d1",
  "v0.3.0 f188b2cb2ee4948ce189eeca9fd7c6d095c8bda9",
  "v0.3.1 3dd996b973cca2d7eecf990f08ce2c4974e22872",
  "v0.3.2 88ad9d8a757cc79a4cdc554e543c565decb4861a",
  "v0.3.3 bcee87c3d7d09db093f92ba825019dd3ec8726a7",
  "v0.3.4 7345c222bd446bad6eb32a32f38cad36867fba7c",
  "v0.4.0 9f3a52558338503571b37c034a12219566f27aa2",
  "v0.4.1 0892f1d426e3d69daaff1251d8e45d2ef60d1ad4"
]

[[packages]]
name = "PLOOC"
releases = [ "v1.0.0 e2a630358c0d490b198f7e8682fb61569eb7ec56" ]

[[packages]]
name = "pikaRTDevice"
releases = [
  "v0.0.1 fe900b79d8d1075bb7e4e3dd9d4e1e187e0c9195",
  "v1.0.0 ac4247e5fd3e221eb110a1b41276849c623049ec",
  "v1.0.1 61e6a7352b656adbce0f2ad82ea1fc992dcbb603",
  "v1.1.0 9f3a52558338503571b37c034a12219566f27aa2"
]

[[packages]]
name = "TemplateDevice"
releases = [ "v0.0.1 281600804a5393c6721eab8ec6160a376ba010b4" ]

[[packages]]
name = "STM32G0"
releases = [
  "v1.0.2 0052a28582ac8a85cc48e1d676d9a3be5cb1b93f",
  "v1.0.3 a150ebe43377852fc91d12be0163950435f71bd5",
  "v1.1.0 59cdf753071da17dcac91f583f4d69ad4587dd93",
  "v1.1.1 f755ec10042f4deefef1c5491f5e91a651f71a1b",
  "v1.2.0 19e644a2ef411aa49016bf106f4be8beeb0827b1",
  "v1.3.0 9f3a52558338503571b37c034a12219566f27aa2",
  "v1.3.1 3119a938dac7a723be3775aaaff5bc337a165567"
]

[[packages]]
name = "STM32F1"
releases = [
  "v1.0.0 04e2988d22c995ed0321eb4361e46867e4347e0a",
  "v1.0.1 355f2253b16fa416ffae59fb35f7c71c75480b12",
  "v1.0.2 4d7209bb174b1df26d22352a757cc43faaff4012",
  "v1.0.3 86377d1a3c19cd01b1dc109180be437373ce7c5f",
  "v1.1.0 186b951078c76b1c80b8111d76097970c21a3004",
  "v1.1.1 567d0b19ce998a290fa538845d107c744ccd0258"
]

[[packages]]
name = "ESP32"
releases = [ "v0.1.0 ee7e38e9422970bba86f5cd7774db8654edd38dc" ]

[[packages]]
name = "STM32F4"
releases = [
  "v0.0.1 5f992314b5ec9f201302eea8df8620e0cde600ae",
  "v0.0.2 8bcb5ad868ec8961f2a3f08329a46ab0b780596b"
]

[[packages]]
name = "PikaPiZero"
releases = [
  "v1.0.0 af42fd61884dc7048628b0d3bafaa42697f6e8ea",
  "v1.0.1 af42fd61884dc7048628b0d3bafaa42697f6e8ea",
  "v1.0.2 8866710f653ad005f5c3edc5e6417ad31075b7d5",
  "v1.0.3 6c6e1b37c6c9f38fc4c7d567a30e212572a68a60",
  "v1.0.4 5ae86929851ff6a62342a7072b77e9cf5be85f1c",
  "v1.0.5 83f2639bf61a3b000a9bae5c5977bd67afdf57d1",
  "v1.1.0 b5d3209cc2b90cb080d0dbb15f901b9cbee9397d",
  "v1.1.1 8dd93fb30169848e77ccc39e003ea4086cdda1b7",
  "v1.1.2 0052a28582ac8a85cc48e1d676d9a3be5cb1b93f",
  "v1.1.3 f755ec10042f4deefef1c5491f5e91a651f71a1b",
  "v1.2.0 9f3a52558338503571b37c034a12219566f27aa2",
  "v1.3.0 9d7b155af3260c0fc00be05598c807b71d7cc198"
]

[[packages]]
name = "CH32V103"
releases = [ "v1.0.0 4ce839297f208b0ac4fc1e7f16fef16ab605e70d" ]


[[packages]]
name = "SmartLoong"
releases = [ "v0.0.1 a5437de66e8cff600be247eae63ac9114b6b153f" ]

[[packages]]
name = "W801Device"
releases = [
  "v0.0.1 88f4e507f1665ca7ceda149aabf029f4e21e22c7",
  "v1.0.0 7ae9cd062fa48ecfe4b843c9f13b0daef0efd79d",
  "v1.1.0 c53bf1483d015555b4823f129864444198227403"
]

[[packages]]
name = "CH582"
releases = [
  "v1.0.0 7cdb0cf9ed161c3fc6802028a9e34c9f94b56244",
  "v1.1.0 bfc01e09fd71c26a7140d23864c1d3052f23d087",
  "v1.1.1 268c8433a1add8c902d694808682890a2df8c1fc"
]

[[packages]]
name = "MM32F5277E9P"
releases = [ "v0.0.1 176232225939eccfaedfea412699a2e53c38ace1" ]

[[packages]]
name = "AIR32F1"
releases = [
  "v0.0.1 9f9579c54ebddb12c66afc8da64a987767ff512f",
  "v0.1.0 faa9c6230149d09188114af7af822e5d34af6b55"
]

