[[packages]]
name = "pikascript-core"
releases = [
  "v0.8.1 af42fd61884dc7048628b0d3bafaa42697f6e8ea",
  "v0.8.2 af42fd61884dc7048628b0d3bafaa42697f6e8ea",
  "v0.8.3 af42fd61884dc7048628b0d3bafaa42697f6e8ea",
  "v0.9.0 332ef8afb0692cddd194782a07e30f2688d0f813",
  "v0.10.0 c86eaefa4516dd82b1050fa74a7d85399459d5ed",
  "v1.0.0 7b816b1546ef91a03f77760d4b10806ab956d452",
  "v1.1.0 845d1fc6520237e2238087800f72608dcb81afa6",
  "v1.1.1 c77e42450ed0eb09fcd7bb2b7d7c2b7eeeb55a2e",
  "v1.1.2 f6ad2c78f49162ab3f898abc6a0a4d87777ce655",
  "v1.1.3 6539072bf7bebb242ea40f8595bfb5c9aae3de7f",
  "v1.2.0 ce3df083b68fbfc85e64e6793fe07a6736d6f29f",
  "v1.2.1 e29a77527fd753c4eb811b047899534472bfc8ec",
  "v1.2.2 5316ede928b01a20571103616a64666abbc40e0a",
  "v1.2.3 5ae86929851ff6a62342a7072b77e9cf5be85f1c",
  "v1.2.4 b7ac057d75e88736cc844de0bafb447a48f2fb6d",
  "v1.2.5 db51f0520a673074a14ef0f5c4434da0d5c3425f",
  "v1.2.6 aafc990cdf1dccf6be1944de8c6456a6135c98b1",
  "v1.2.7 1c469e1871002df28b0c531828e20f283dc15d36",
  "v1.2.8 3ad17a46b83eec46d2c493761a67ab0d0c492159",
  "v1.2.9 c35940141816c74e164c83c38bcdab7d6ffe1a2f",
  "v1.3.0 3032d3d05423b5f3dd2a4efe1f8eadd1d835f58f",
  "v1.3.1 343a1d56c53bba78fce9a0cd0cc8dfcd580632be",
  "v1.3.2 b54cd1ed5ae45c4f5789e266ea1f4f2e420ec306",
  "v1.3.3 520a1cfb49e7c9e6bfca84a140fd80b0c2b0e000",
  "v1.3.4 c205fc00f1503135bdf6890ebfb61ebaf7d23445",
  "v1.3.5 80d255e8efbf718a7bd6cac9cf8478a6e2e72a37",
  "lts2021 80d255e8efbf718a7bd6cac9cf8478a6e2e72a37",
  "v1.3.5.1 9ebdaa5560c04f53af13743d00a5b7a8f00c0508",
]

[[packages]]
name = "PikaStdLib"
releases = [
  "v1.0.1 af42fd61884dc7048628b0d3bafaa42697f6e8ea",
  "v1.1.0 0b3b866dbacc363c7b6b3899faa0cbcaccd59d5e",
  "v1.2.0 ca29e112687525ee7511bd30418d368754627a00",
  "v1.2.1 5ae86929851ff6a62342a7072b77e9cf5be85f1c",
  "v1.2.2 b7ac057d75e88736cc844de0bafb447a48f2fb6d",
  "v1.2.3 85aa32b4831ede9de2657dd4cdd22e1310b1cde8",
  "v1.2.4 3ad17a46b83eec46d2c493761a67ab0d0c492159",
  "v1.2.5 c35940141816c74e164c83c38bcdab7d6ffe1a2f",
  "v1.3.0 5eedf8be911f4c389c5496a79b600004077039f5",
  "v1.3.1 343a1d56c53bba78fce9a0cd0cc8dfcd580632be",
  "v1.3.2 b54cd1ed5ae45c4f5789e266ea1f4f2e420ec306",
  "v1.3.3 520a1cfb49e7c9e6bfca84a140fd80b0c2b0e000",
  "v1.3.4 c205fc00f1503135bdf6890ebfb61ebaf7d23445",
  "v1.3.5 3e87db85ca2171991f77bd3af59c4eaefed69110",
  "lts2021 3e87db85ca2171991f77bd3af59c4eaefed69110",
  "v1.3.5.1 9ebdaa5560c04f53af13743d00a5b7a8f00c0508",
]

[[packages]]
name = "PikaStdDevice"
releases = [
  "v1.3.0 af42fd61884dc7048628b0d3bafaa42697f6e8ea",
  "v1.4.0 29c3c5b3b0cb4d3e41e6a2a0aef9e2826bc6f7ba",
  "v1.4.1 6539072bf7bebb242ea40f8595bfb5c9aae3de7f",
  "v1.4.2 5ae86929851ff6a62342a7072b77e9cf5be85f1c",
  "v1.4.3 17cc05c42cc26e694475a6c19f8d0712f8768750",
]

[[packages]]
name = "STM32G0"
releases = [
  "v1.0.2 0052a28582ac8a85cc48e1d676d9a3be5cb1b93f",
  "v1.0.3 a150ebe43377852fc91d12be0163950435f71bd5",
  "v1.1.0 59cdf753071da17dcac91f583f4d69ad4587dd93",
  "v1.1.1 0ba473d207606cf19c8b2dbbcd6d1ed29fe0eaf7",
]

[[packages]]
name = "PikaPiZero"
releases = [
  "v1.0.0 af42fd61884dc7048628b0d3bafaa42697f6e8ea",
  "v1.0.1 af42fd61884dc7048628b0d3bafaa42697f6e8ea",
  "v1.0.2 8866710f653ad005f5c3edc5e6417ad31075b7d5",
  "v1.0.3 6c6e1b37c6c9f38fc4c7d567a30e212572a68a60",
  "v1.0.4 5ae86929851ff6a62342a7072b77e9cf5be85f1c",
  "v1.0.5 83f2639bf61a3b000a9bae5c5977bd67afdf57d1",
  "v1.1.0 b5d3209cc2b90cb080d0dbb15f901b9cbee9397d",
  "v1.1.1 8dd93fb30169848e77ccc39e003ea4086cdda1b7",
  "v1.1.2 0052a28582ac8a85cc48e1d676d9a3be5cb1b93f",
  "v1.1.3 fdbaf8addffc30f947aad653b4165947c6fcff3d",
]

[[packages]]
name = "Arm2D"
releases = [
  "v0.0.1 af42fd61884dc7048628b0d3bafaa42697f6e8ea",
  "v0.1.0 1b0384c5b20e336645b24df808f98548912405b8",
  "v0.2.0 83f2639bf61a3b000a9bae5c5977bd67afdf57d1",
  "v0.3.0 f188b2cb2ee4948ce189eeca9fd7c6d095c8bda9",
  "v0.3.1 3dd996b973cca2d7eecf990f08ce2c4974e22872",
  "v0.3.2 88ad9d8a757cc79a4cdc554e543c565decb4861a",
]

[[packages]]
name = "CH32V103"
releases = [
  "v1.0.0 4ce839297f208b0ac4fc1e7f16fef16ab605e70d",
]

[[packages]]
name = "STM32F1"
releases = [
  "v1.0.0 04e2988d22c995ed0321eb4361e46867e4347e0a",
  "v1.0.1 355f2253b16fa416ffae59fb35f7c71c75480b12",
  "v1.0.2 4d7209bb174b1df26d22352a757cc43faaff4012",
  "v1.0.3 86377d1a3c19cd01b1dc109180be437373ce7c5f",
]

[[packages]]
name = "pikaRTThread"
releases = [
  "v1.0.0 3509764a2ed63c565e63f61814e9b656fc573841",
  "v1.0.1 e8bb5a8d18516f79da7115f73024cae70fa51590",
  "v1.1.0 ff2e72ccb08c6a5935ed7ed77dfaa3a074ff120f",
]

[[packages]]
name = "pikaRTDevice"
releases = [
  "v0.0.1 fe900b79d8d1075bb7e4e3dd9d4e1e187e0c9195",
]

[[packages]]
name = "SmartLoong"
releases = [
  "v0.0.1 a5437de66e8cff600be247eae63ac9114b6b153f",
]

[[packages]]
name = "PikaVSF"
releases = [
  "v0.0.1 30c122eecd2f835d9c67e3054b8ee1c477d469b8",
]

[[packages]]
name = "W801Device"
releases = [
  "v0.0.1 88f4e507f1665ca7ceda149aabf029f4e21e22c7",
]
